/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenixpro_controls_jni_ControlConfigJNI */

#ifndef _Included_com_ctre_phoenixpro_controls_jni_ControlConfigJNI
#define _Included_com_ctre_phoenixpro_controls_jni_ControlConfigJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenixpro_controls_jni_ControlConfigJNI
 * Method:    JNI_RequestConfigApply
 * Signature: (Ljava/lang/String;IDLjava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenixpro_controls_jni_ControlConfigJNI_JNI_1RequestConfigApply
  (JNIEnv *, jclass, jstring, jint, jdouble, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif

