/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenixpro_jni_ErrorReportingJNI */

#ifndef _Included_com_ctre_phoenixpro_jni_ErrorReportingJNI
#define _Included_com_ctre_phoenixpro_jni_ErrorReportingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenixpro_jni_ErrorReportingJNI
 * Method:    reportStatusCode
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenixpro_jni_ErrorReportingJNI_reportStatusCode
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif

