/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenixpro_Utils */

#ifndef _Included_com_ctre_phoenixpro_Utils
#define _Included_com_ctre_phoenixpro_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenixpro_Utils
 * Method:    getCurrentTimeSeconds
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenixpro_Utils_getCurrentTimeSeconds
  (JNIEnv *, jclass);

/*
 * Class:     com_ctre_phoenixpro_Utils
 * Method:    isSimulation
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctre_phoenixpro_Utils_isSimulation
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

