/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenixpro_hardware_jni_HardwareJNI */

#ifndef _Included_com_ctre_phoenixpro_hardware_jni_HardwareJNI
#define _Included_com_ctre_phoenixpro_hardware_jni_HardwareJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenixpro_hardware_jni_HardwareJNI
 * Method:    getDeviceHash
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenixpro_hardware_jni_HardwareJNI_getDeviceHash
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif

