/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenix6_jni_CANBusJNI */

#ifndef _Included_com_ctre_phoenix6_jni_CANBusJNI
#define _Included_com_ctre_phoenix6_jni_CANBusJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenix6_jni_CANBusJNI
 * Method:    JNI_IsNetworkFD
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctre_phoenix6_jni_CANBusJNI_JNI_1IsNetworkFD
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ctre_phoenix6_jni_CANBusJNI
 * Method:    JNI_GetStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_CANBusJNI_JNI_1GetStatus
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif

