/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenix6_jni_OrchestraJNI */

#ifndef _Included_com_ctre_phoenix6_jni_OrchestraJNI
#define _Included_com_ctre_phoenix6_jni_OrchestraJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_Create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1Create
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1Close
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_AddDevice
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1AddDevice
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_AddDeviceWithTrack
 * Signature: (Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1AddDeviceWithTrack
  (JNIEnv *, jobject, jstring, jlong, jint);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_ClearDevices
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1ClearDevices
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_LoadMusic
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1LoadMusic
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_Play
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1Play
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_Pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1Pause
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1Stop
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_IsPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1IsPlaying
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_OrchestraJNI
 * Method:    JNI_GetCurrentTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenix6_jni_OrchestraJNI_JNI_1GetCurrentTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

