/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenix6_controls_jni_ControlJNI */

#ifndef _Included_com_ctre_phoenix6_controls_jni_ControlJNI
#define _Included_com_ctre_phoenix6_controls_jni_ControlJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlEmpty
 * Signature: (Ljava/lang/String;IDZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlEmpty
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDutyCycleOut
 * Signature: (Ljava/lang/String;IDZDZZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDutyCycleOut
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlTorqueCurrentFOC
 * Signature: (Ljava/lang/String;IDZDDDZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlTorqueCurrentFOC
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlVoltageOut
 * Signature: (Ljava/lang/String;IDZDZZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlVoltageOut
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlPositionDutyCycle
 * Signature: (Ljava/lang/String;IDZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlPositionDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlPositionVoltage
 * Signature: (Ljava/lang/String;IDZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlPositionVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlPositionTorqueCurrentFOC
 * Signature: (Ljava/lang/String;IDZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlPositionTorqueCurrentFOC
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlVelocityDutyCycle
 * Signature: (Ljava/lang/String;IDZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlVelocityDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlVelocityVoltage
 * Signature: (Ljava/lang/String;IDZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlVelocityVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlVelocityTorqueCurrentFOC
 * Signature: (Ljava/lang/String;IDZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlVelocityTorqueCurrentFOC
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicDutyCycle
 * Signature: (Ljava/lang/String;IDZDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicVoltage
 * Signature: (Ljava/lang/String;IDZDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicTorqueCurrentFOC
 * Signature: (Ljava/lang/String;IDZDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicTorqueCurrentFOC
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialDutyCycle
 * Signature: (Ljava/lang/String;IDZDDZIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialVoltage
 * Signature: (Ljava/lang/String;IDZDDZIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialPositionDutyCycle
 * Signature: (Ljava/lang/String;IDZDDZIIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialPositionDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialPositionVoltage
 * Signature: (Ljava/lang/String;IDZDDZIIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialPositionVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialVelocityDutyCycle
 * Signature: (Ljava/lang/String;IDZDDZIIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialVelocityDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialVelocityVoltage
 * Signature: (Ljava/lang/String;IDZDDZIIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialVelocityVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialMotionMagicDutyCycle
 * Signature: (Ljava/lang/String;IDZDDZIIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialMotionMagicDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialMotionMagicVoltage
 * Signature: (Ljava/lang/String;IDZDDZIIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialMotionMagicVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jint, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlFollower
 * Signature: (Ljava/lang/String;IDZIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlFollower
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jint, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlStrictFollower
 * Signature: (Ljava/lang/String;IDZI)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlStrictFollower
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jint);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialFollower
 * Signature: (Ljava/lang/String;IDZIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialFollower
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jint, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDifferentialStrictFollower
 * Signature: (Ljava/lang/String;IDZI)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDifferentialStrictFollower
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jint);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlNeutralOut
 * Signature: (Ljava/lang/String;IDZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlNeutralOut
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlCoastOut
 * Signature: (Ljava/lang/String;IDZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlCoastOut
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlStaticBrake
 * Signature: (Ljava/lang/String;IDZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlStaticBrake
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlBalanceBattery
 * Signature: (Ljava/lang/String;IDZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlBalanceBattery
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlBMSManualIsolator
 * Signature: (Ljava/lang/String;IDZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlBMSManualIsolator
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlBMSManualVboost
 * Signature: (Ljava/lang/String;IDZZDD)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlBMSManualVboost
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jboolean, jdouble, jdouble);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlBMSManualPwmJunction
 * Signature: (Ljava/lang/String;IDZID)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlBMSManualPwmJunction
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jint, jdouble);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlBMSClearFault
 * Signature: (Ljava/lang/String;IDZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlBMSClearFault
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMusicTone
 * Signature: (Ljava/lang/String;IDZD)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMusicTone
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicVelocityDutyCycle
 * Signature: (Ljava/lang/String;IDZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicVelocityDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicVelocityTorqueCurrentFOC
 * Signature: (Ljava/lang/String;IDZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicVelocityTorqueCurrentFOC
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicVelocityVoltage
 * Signature: (Ljava/lang/String;IDZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicVelocityVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicExpoDutyCycle
 * Signature: (Ljava/lang/String;IDZDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicExpoDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicExpoVoltage
 * Signature: (Ljava/lang/String;IDZDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicExpoVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlMotionMagicExpoTorqueCurrentFOC
 * Signature: (Ljava/lang/String;IDZDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlMotionMagicExpoTorqueCurrentFOC
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDynamicMotionMagicDutyCycle
 * Signature: (Ljava/lang/String;IDZDDDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDynamicMotionMagicDutyCycle
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDynamicMotionMagicVoltage
 * Signature: (Ljava/lang/String;IDZDDDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDynamicMotionMagicVoltage
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDynamicMotionMagicTorqueCurrentFOC
 * Signature: (Ljava/lang/String;IDZDDDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDynamicMotionMagicTorqueCurrentFOC
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_DutyCycleOut_Position
 * Signature: (Ljava/lang/String;IDZDZZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1DutyCycleOut_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_PositionDutyCycle_Position
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1PositionDutyCycle_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VelocityDutyCycle_Position
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VelocityDutyCycle_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_MotionMagicDutyCycle_Position
 * Signature: (Ljava/lang/String;IDZDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1MotionMagicDutyCycle_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_DutyCycleOut_Velocity
 * Signature: (Ljava/lang/String;IDZDZZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1DutyCycleOut_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_PositionDutyCycle_Velocity
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1PositionDutyCycle_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VelocityDutyCycle_Velocity
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VelocityDutyCycle_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_MotionMagicDutyCycle_Velocity
 * Signature: (Ljava/lang/String;IDZDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1MotionMagicDutyCycle_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VoltageOut_Position
 * Signature: (Ljava/lang/String;IDZDZZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VoltageOut_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_PositionVoltage_Position
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1PositionVoltage_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VelocityVoltage_Position
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VelocityVoltage_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_MotionMagicVoltage_Position
 * Signature: (Ljava/lang/String;IDZDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1MotionMagicVoltage_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VoltageOut_Velocity
 * Signature: (Ljava/lang/String;IDZDZZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VoltageOut_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_PositionVoltage_Velocity
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1PositionVoltage_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VelocityVoltage_Velocity
 * Signature: (Ljava/lang/String;IDZDDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VelocityVoltage_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_MotionMagicVoltage_Velocity
 * Signature: (Ljava/lang/String;IDZDZDIZZZDDZDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1MotionMagicVoltage_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jboolean, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_TorqueCurrentFOC_Position
 * Signature: (Ljava/lang/String;IDZDDDZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1TorqueCurrentFOC_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_PositionTorqueCurrentFOC_Position
 * Signature: (Ljava/lang/String;IDZDDDIZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1PositionTorqueCurrentFOC_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VelocityTorqueCurrentFOC_Position
 * Signature: (Ljava/lang/String;IDZDDDIZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VelocityTorqueCurrentFOC_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_MotionMagicTorqueCurrentFOC_Position
 * Signature: (Ljava/lang/String;IDZDDIZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1MotionMagicTorqueCurrentFOC_1Position
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_TorqueCurrentFOC_Velocity
 * Signature: (Ljava/lang/String;IDZDDDZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1TorqueCurrentFOC_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_PositionTorqueCurrentFOC_Velocity
 * Signature: (Ljava/lang/String;IDZDDDIZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1PositionTorqueCurrentFOC_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_VelocityTorqueCurrentFOC_Velocity
 * Signature: (Ljava/lang/String;IDZDDDIZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1VelocityTorqueCurrentFOC_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

/*
 * Class:     com_ctre_phoenix6_controls_jni_ControlJNI
 * Method:    JNI_RequestControlDiff_MotionMagicTorqueCurrentFOC_Velocity
 * Signature: (Ljava/lang/String;IDZDDIZZZDDDIZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_controls_jni_ControlJNI_JNI_1RequestControlDiff_1MotionMagicTorqueCurrentFOC_1Velocity
  (JNIEnv *, jclass, jstring, jint, jdouble, jboolean, jdouble, jdouble, jint, jboolean, jboolean, jboolean, jdouble, jdouble, jdouble, jint, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif

