/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenix6_jni_SignalLoggerJNI */

#ifndef _Included_com_ctre_phoenix6_jni_SignalLoggerJNI
#define _Included_com_ctre_phoenix6_jni_SignalLoggerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_SetLoggerPath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1SetLoggerPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_StartLogger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1StartLogger
  (JNIEnv *, jclass);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_StopLogger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1StopLogger
  (JNIEnv *, jclass);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_EnableAutoLogging
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1EnableAutoLogging
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteRaw
 * Signature: (Ljava/lang/String;[BD)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteRaw
  (JNIEnv *, jclass, jstring, jbyteArray, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteBoolean
 * Signature: (Ljava/lang/String;ZD)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteBoolean
  (JNIEnv *, jclass, jstring, jboolean, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteInteger
 * Signature: (Ljava/lang/String;JLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteInteger
  (JNIEnv *, jclass, jstring, jlong, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteFloat
 * Signature: (Ljava/lang/String;FLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteFloat
  (JNIEnv *, jclass, jstring, jfloat, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteDouble
 * Signature: (Ljava/lang/String;DLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteDouble
  (JNIEnv *, jclass, jstring, jdouble, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteString
 * Signature: (Ljava/lang/String;Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteString
  (JNIEnv *, jclass, jstring, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteBooleanArray
 * Signature: (Ljava/lang/String;[ZD)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteBooleanArray
  (JNIEnv *, jclass, jstring, jbooleanArray, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteIntegerArray
 * Signature: (Ljava/lang/String;[JLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteIntegerArray
  (JNIEnv *, jclass, jstring, jlongArray, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteFloatArray
 * Signature: (Ljava/lang/String;[FLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteFloatArray
  (JNIEnv *, jclass, jstring, jfloatArray, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_SignalLoggerJNI
 * Method:    JNI_WriteDoubleArray
 * Signature: (Ljava/lang/String;[DLjava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_SignalLoggerJNI_JNI_1WriteDoubleArray
  (JNIEnv *, jclass, jstring, jdoubleArray, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif

