/*
 * Copyright (C) Cross The Road Electronics.  All rights reserved.
 * License information can be found in CTRE_LICENSE.txt
 * For support and suggestions contact support@ctr-electronics.com or file
 * an issue tracker at https://github.com/CrossTheRoadElec/Phoenix-Releases
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenix6_jni_StatusSignalJNI */

#ifndef _Included_com_ctre_phoenix6_jni_StatusSignalJNI
#define _Included_com_ctre_phoenix6_jni_StatusSignalJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenix6_jni_StatusSignalJNI
 * Method:    JNI_GetUnits
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ctre_phoenix6_jni_StatusSignalJNI_JNI_1GetUnits
  (JNIEnv *, jobject);

/*
 * Class:     com_ctre_phoenix6_jni_StatusSignalJNI
 * Method:    JNI_RefreshSignal
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_StatusSignalJNI_JNI_1RefreshSignal
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_StatusSignalJNI
 * Method:    JNI_WaitForSignal
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_StatusSignalJNI_JNI_1WaitForSignal
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_ctre_phoenix6_jni_StatusSignalJNI
 * Method:    JNI_WaitForAll
 * Signature: (Ljava/lang/String;D[Lcom/ctre/phoenix6/jni/StatusSignalJNI;)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_StatusSignalJNI_JNI_1WaitForAll
  (JNIEnv *, jclass, jstring, jdouble, jobjectArray);

/*
 * Class:     com_ctre_phoenix6_jni_StatusSignalJNI
 * Method:    JNI_SetUpdateFrequency
 * Signature: (Ljava/lang/String;DD)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix6_jni_StatusSignalJNI_JNI_1SetUpdateFrequency
  (JNIEnv *, jobject, jstring, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif

